### ISSUE TITLE
Issues with using actionlib to control the Vogui via a script

### ISSUE THREAD

**Issue by JamesKeegan1** [RobotnikAutomation/rbvogui_sim#3] opened 2021-10-06 08:59 UTC
I am currently very confused as to how to control the Vogui via a script. I have tried adapting some code I found on the internet with no luck. Is there any reference code or documentation to explain how to do this in a practical manner?

**Comment by robert-ros** [comment] 2021-10-08 16:24
Duplicate of #2

**Closed as completed by robert-ros** 2021-10-08 16:24 UTC
